import React, { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ArrowRight, BarChart3, Check, ChefHat, ClipboardList, ExternalLink, Menu, MonitorPlay, Package, Printer, QrCode, ShieldCheck, X } from 'lucide-react';

const APP_URL = import.meta.env.VITE_RESTAURANT_APP_URL || 'https://mudavim-pos-staging.web.app';
const DEMO_MENU_URL = `${APP_URL}/menu/bi-restoran-demo/location_bi_restoran_demo_main`;
const INTERACTIVE_DEMO_URL = `${APP_URL}/demo`;
const CONTACT_EMAIL = 'saasadmin@bianalytic.net';

const features = [
  { icon: ClipboardList, title: 'Salon ve sipariş yönetimi', text: 'Masaları, adisyonları ve sipariş durumlarını tek ekrandan yönetin.' },
  { icon: ChefHat, title: 'Canlı mutfak akışı', text: 'Siparişler mutfağa anında ulaşsın; hazırlanıyor, hazır ve servis durumları senkron kalsın.' },
  { icon: Printer, title: 'Termal yazıcı desteği', text: 'Mutfak ve müşteri fişlerini uygun yazıcıya yönlendirin, başarısız işleri tekrar deneyin.' },
  { icon: QrCode, title: 'Dinamik QR menü', text: 'Ürün, fiyat ve stok değişiklikleri müşterinin mobil menüsüne otomatik yansısın.' },
  { icon: Package, title: 'Stok, reçete ve fire', text: 'Hammadde tüketimini, reçete maliyetlerini ve ürün bazlı israfı takip edin.' },
  { icon: BarChart3, title: 'Yönetim raporları', text: 'Ciro, ürün performansı, hazırlama süresi ve kârlılık metriklerini görün.' },
];

const flow = [
  ['01', 'Restoranınızı oluşturun', 'İşletme ve şube bilgilerinizi birkaç adımda tanımlayın.'],
  ['02', 'Menü ve masaları hazırlayın', 'Ürünleri, kategorileri, fiyatları ve salon düzenini ekleyin.'],
  ['03', 'Ekibinizi davet edin', 'Garson, mutfak ve yönetici rollerini güvenli biçimde atayın.'],
  ['04', 'Operasyona başlayın', 'Siparişten servise, hesaptan rapora bütün akışı tek yerden yönetin.'],
];

const showcase = [
  { image: '/showcase-demo-dashboard.png', eyebrow: 'Yönetici dashboard', title: 'Ciro, maliyet ve kârlılık tek bakışta', text: 'Günlük kapanışlar, gıda maliyeti, operasyon gideri ve net kâr aynı raporlama ekranında izlenir.' },
  { image: '/showcase-demo-salon.png', eyebrow: 'Canlı salon', title: 'Masaların durumu anlık görünür', text: 'Boş, dolu, rezerve, mutfakta ve servise hazır masalar tek operasyon ekranında takip edilir.' },
  { image: '/showcase-demo-kitchen.png', eyebrow: 'Mutfak akışı', title: 'Siparişler mutfakta kaybolmaz', text: 'Yeni, hazırlanıyor ve hazır siparişler mutfak ekibinin kullanacağı sade ekranda yönetilir.' },
  { image: '/showcase-demo-qr-menu.png', eyebrow: 'Dinamik QR menü', title: 'Ürünler müşterinin telefonunda güncel kalır', text: 'Kategori, fiyat ve bulunabilirlik değişiklikleri POS sistemiyle senkronize mobil menüde yayınlanır.' },
];

function ProductNav() {
  const [open, setOpen] = useState(false);
  const links = [['Özellikler', '#ozellikler'], ['Ürün Ekranları', '#urun-ekranlari'], ['Nasıl çalışır?', '#nasil-calisir'], ['Paketler', '#paketler'], ['SSS', '#sss']];
  return <header className="fixed inset-x-0 top-0 z-50 border-b border-slate-200/80 bg-[#fffdf8]/90 backdrop-blur-xl">
    <div className="mx-auto flex h-20 max-w-[1600px] items-center justify-between gap-4 px-4 sm:px-6 lg:px-8">
      <a href="/restoran" className="flex shrink-0 items-center gap-3" aria-label="Bi Restoran ana sayfa"><img src="/bi-restoran-logo.jpg" alt="Bi Restoran" className="h-14 w-14 rounded-2xl border border-slate-200 bg-white object-cover shadow-sm"/><span><strong className="block font-display text-xl leading-none text-navy-900">Bi Restoran</strong><small className="mt-1 block text-[10px] font-bold uppercase tracking-[.2em] text-teal-600">Analytics &amp; Flavor</small></span></a>
      <nav className="hidden shrink-0 items-center gap-6 min-[1536px]:flex">{links.map(([label, href]) => <a key={href} href={href} className="whitespace-nowrap text-sm font-semibold text-slate-600 transition hover:text-teal-600">{label}</a>)}</nav>
      <div className="hidden shrink-0 items-center gap-2 sm:flex"><a href={INTERACTIVE_DEMO_URL} target="_blank" rel="noreferrer" className="inline-flex whitespace-nowrap items-center gap-2 rounded-full border border-teal-600/25 bg-teal-50 px-4 py-2.5 text-sm font-bold text-teal-700 transition hover:bg-teal-100"><MonitorPlay size={16}/> Demo App</a><a href={DEMO_MENU_URL} className="inline-flex whitespace-nowrap items-center gap-2 rounded-full border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-navy-900 transition hover:border-teal-300"><QrCode size={16}/> QR Menü</a><a href={APP_URL} target="_blank" rel="noreferrer" className="whitespace-nowrap px-3 py-2.5 text-sm font-bold text-navy-900">Giriş Yap</a><a href={`${APP_URL}/signup`} target="_blank" rel="noreferrer" className="hidden whitespace-nowrap items-center gap-2 rounded-full bg-navy-900 px-5 py-3 text-sm font-bold text-white min-[1280px]:inline-flex">14 Gün Ücretsiz Dene <ArrowRight size={16}/></a></div>
      <button type="button" onClick={() => setOpen(!open)} className="rounded-xl border border-slate-200 p-2.5 text-navy-900 sm:hidden" aria-label="Menüyü aç">{open ? <X/> : <Menu/>}</button>
    </div>
    <AnimatePresence>{open && <motion.div initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} className="overflow-hidden border-t border-slate-100 bg-white sm:hidden"><div className="space-y-1 p-4"><div className="mb-3 grid grid-cols-2 gap-2"><a href={INTERACTIVE_DEMO_URL} target="_blank" rel="noreferrer" className="flex items-center justify-center gap-2 rounded-xl bg-teal-50 px-3 py-3 font-bold text-teal-700"><MonitorPlay size={17}/> Demo App</a><a href={DEMO_MENU_URL} className="flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-3 py-3 font-bold text-navy-900"><QrCode size={17}/> QR Menü</a></div>{links.map(([label, href]) => <a key={href} href={href} onClick={() => setOpen(false)} className="block rounded-xl px-4 py-3 font-semibold text-navy-900">{label}</a>)}<a href={APP_URL} className="block rounded-xl px-4 py-3 font-semibold text-navy-900">Giriş Yap</a><a href={`${APP_URL}/signup`} className="mt-2 block rounded-xl bg-navy-900 px-4 py-3 text-center font-bold text-white">14 Gün Ücretsiz Dene</a></div></motion.div>}</AnimatePresence>
  </header>;
}

function ProductHero() {
  const tables = [['Masa 4','Dolu','₺1.240'],['Masa 7','Hazır','₺860'],['Masa 12','Mutfakta','₺2.150'],['Masa 2','Boş','—'],['Masa 9','Hesap','₺740'],['Masa 15','Dolu','₺1.580']];
  return <section className="relative overflow-hidden bg-[#fffdf8] pb-20 pt-36 lg:pb-28 lg:pt-44"><div className="absolute -right-40 top-20 h-[34rem] w-[34rem] rounded-full bg-teal-400/10 blur-3xl"/><div className="mx-auto grid max-w-7xl items-center gap-14 px-4 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:px-8">
    <motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}}><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-teal-600/20 bg-teal-600/10 px-4 py-2 text-sm font-bold text-teal-600"><span className="h-2 w-2 rounded-full bg-teal-600"/> Restoran operasyonu, tek merkezde</div><h1 className="max-w-3xl font-display text-5xl font-bold leading-[1.05] tracking-tight text-navy-900 sm:text-6xl lg:text-7xl">Servisten rapora, restoranınızın <span className="text-teal-600">dijital işletim sistemi.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-600">Salon, mutfak, QR menü, stok, fiş ve raporlamayı aynı akışta buluşturan bulut tabanlı restoran yönetim platformu.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href={`${APP_URL}/signup`} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-full bg-teal-600 px-7 py-4 font-bold text-white shadow-xl">14 Gün Ücretsiz Başla <ArrowRight size={18}/></a><a href={DEMO_MENU_URL} className="inline-flex items-center justify-center gap-2 rounded-full border border-slate-300 bg-white px-7 py-4 font-bold text-navy-900"><QrCode size={18}/> Canlı Demo Menüyü Aç</a></div><div className="mt-6 flex flex-wrap gap-x-6 gap-y-2 text-sm font-medium text-slate-500">{['Kredi kartı gerekmez','14 gün deneme','Mobil uyumlu'].map(x=><span key={x} className="flex items-center gap-2"><Check size={16} className="text-teal-600"/>{x}</span>)}</div></motion.div>
    <motion.div initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} transition={{delay:.15}} className="relative"><div className="absolute inset-6 rounded-[2.5rem] bg-navy-900/15 blur-3xl"/><div className="relative rounded-[2rem] border border-white/80 bg-navy-900 p-4 shadow-2xl"><div className="rounded-[1.4rem] bg-[#f7f7f4] p-5 sm:p-7"><div className="mb-6 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-slate-400">Canlı operasyon</p><h2 className="mt-1 font-display text-xl font-bold text-navy-900">Akşam Servisi</h2></div><span className="rounded-full bg-emerald-100 px-3 py-1.5 text-xs font-bold text-emerald-700">● Aktif</span></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{tables.map(([table,status,total])=><div key={table} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><strong>{table}</strong><span className={`h-2.5 w-2.5 rounded-full ${status==='Boş'?'bg-slate-300':status==='Hazır'?'bg-emerald-400':status==='Mutfakta'?'bg-amber-400':'bg-rose-500'}`}/></div><p className="mt-4 text-xs font-semibold text-slate-400">{status}</p><p className="mt-1 font-bold">{total}</p></div>)}</div><div className="mt-4 grid grid-cols-3 gap-3 rounded-2xl bg-white p-4 text-center shadow-sm"><div><strong className="block text-lg">24</strong><small className="text-slate-400">Sipariş</small></div><div className="border-x border-slate-100"><strong className="block text-lg">8 dk</strong><small className="text-slate-400">Hazırlık</small></div><div><strong className="block text-lg text-teal-600">₺18.420</strong><small className="text-slate-400">Ciro</small></div></div></div></div></motion.div>
  </div></section>;
}

export default function RestaurantProduct() {
  useEffect(() => { document.title='Bi Restoran | Bulut Tabanlı Restoran POS ve Yönetim Sistemi'; const el=document.querySelector('meta[name="description"]') || document.head.appendChild(document.createElement('meta')); el.setAttribute('name','description'); el.setAttribute('content','Salon, mutfak, QR menü, stok, termal yazıcı ve raporlamayı tek platformda birleştiren bulut tabanlı restoran yönetim sistemi.'); const favicon=document.querySelector<HTMLLinkElement>('link[rel="icon"]') || document.head.appendChild(document.createElement('link')); favicon.rel='icon'; favicon.type='image/jpeg'; favicon.href='/bi-restoran-logo.jpg'; }, []);
  return <div className="min-h-screen bg-[#fffdf8] font-sans text-navy-900"><ProductNav/><main><ProductHero/>
    <section className="border-y border-slate-200 bg-white py-7"><div className="mx-auto flex max-w-7xl flex-wrap justify-center gap-x-12 gap-y-4 px-4 text-sm font-bold text-slate-500">{['Garson','Mutfak','Yönetim','QR Menü','Termal Yazıcı','Raporlama'].map(x=><span key={x}>{x}</span>)}</div></section>
    <section id="ozellikler" className="bg-white py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-teal-600">Tek platform</p><h2 className="mt-3 font-display text-4xl font-bold sm:text-5xl">Yoğun servis için sade, yönetim için güçlü.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Ekiplerin ihtiyacı olan ekranları role göre sunar; restoran sahibine operasyonun tamamını gösterir.</p></div><div className="mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{features.map(({icon:Icon,title,text})=><article key={title} className="rounded-3xl border border-slate-200 bg-[#fffdf8] p-7 transition hover:-translate-y-1 hover:shadow-xl"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-teal-600/10 text-teal-600"><Icon/></span><h3 className="mt-6 font-display text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></article>)}</div></div></section>
    <section id="urun-ekranlari" className="scroll-mt-20 bg-[#f3f7f6] py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="text-center"><p className="text-sm font-bold uppercase tracking-[.2em] text-teal-600">Dolu demo restoranından gerçek ekranlar</p><h2 className="mt-3 font-display text-4xl font-bold sm:text-5xl">Operasyonun tamamını çalışırken görün.</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-slate-600">Bi Restoran Demo çalışma alanı; örnek ürün, masa, sipariş, stok ve rapor verileriyle yalnız tanıtım amacıyla hazırlanmıştır.</p><a href={DEMO_MENU_URL} className="mt-7 inline-flex items-center gap-2 rounded-full bg-navy-900 px-6 py-3.5 font-bold text-white shadow-lg"><QrCode size={18}/> Salt-okunur canlı menüyü incele <ExternalLink size={16}/></a></div><div className="mt-14 grid gap-7 md:grid-cols-2">{showcase.map(({image,eyebrow,title,text})=><article key={title} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-lg shadow-slate-900/5"><div className="aspect-[16/10] overflow-hidden border-b border-slate-200 bg-slate-100"><img src={image} alt={title} loading="lazy" className="h-full w-full object-cover object-top transition duration-500 hover:scale-[1.02]"/></div><div className="p-7"><p className="text-xs font-bold uppercase tracking-[.18em] text-teal-600">{eyebrow}</p><h3 className="mt-3 font-display text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></div></article>)}</div></div></section>
    <section id="canli-demo" className="bg-white py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-teal-600">Gerçek POS ürün turu</p><h2 className="mt-3 font-display text-4xl font-bold sm:text-5xl">Müşterilerinizin kullanacağı ekranları deneyin.</h2><p className="mt-4 max-w-2xl text-lg leading-8 text-slate-600">Bu demo gerçek Bi Restoran bileşenlerini kullanır. İşlemler yalnızca tarayıcınızda çalışır; Firestore, ödeme ve fiziksel yazıcı servislerine bağlanmaz.</p></div><a href={INTERACTIVE_DEMO_URL} target="_blank" rel="noreferrer" className="inline-flex shrink-0 items-center justify-center gap-2 rounded-full bg-navy-900 px-6 py-3.5 font-bold text-white">Tam Ekran Demoyu Aç <ExternalLink size={17}/></a></div><div className="mt-10 overflow-hidden rounded-[2rem] border border-slate-200 bg-stone-100 shadow-2xl shadow-slate-900/10"><div className="flex items-center gap-2 border-b border-slate-200 bg-white px-5 py-3"><span className="h-3 w-3 rounded-full bg-rose-400"/><span className="h-3 w-3 rounded-full bg-amber-400"/><span className="h-3 w-3 rounded-full bg-emerald-400"/><span className="ml-3 text-xs font-bold text-slate-400">Gerçek Bi Restoran POS · Güvenli Demo Modu</span></div><iframe title="Bi Restoran interaktif demo" src={INTERACTIVE_DEMO_URL} sandbox="allow-scripts allow-same-origin" loading="lazy" className="h-[760px] w-full bg-[#f5f4ef]"/></div></div></section>
    <section id="nasil-calisir" className="bg-navy-900 py-24 text-white"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><p className="text-sm font-bold uppercase tracking-[.2em] text-teal-400">Kurulum akışı</p><h2 className="mt-3 max-w-2xl font-display text-4xl font-bold sm:text-5xl">Dakikalar içinde hesabınızı hazırlayın.</h2><div className="mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{flow.map(([no,title,text])=><div key={no} className="rounded-3xl border border-white/10 bg-white/5 p-6"><span className="font-display text-3xl font-bold text-teal-400">{no}</span><h3 className="mt-8 text-lg font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-300">{text}</p></div>)}</div></div></section>
    <section id="paketler" className="py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="text-center"><p className="text-sm font-bold uppercase tracking-[.2em] text-teal-600">Esnek paketler</p><h2 className="mt-3 font-display text-4xl font-bold">İşletmenizle birlikte büyür.</h2><p className="mt-4 text-slate-600">Önce ücretsiz deneyin. İhtiyacınıza uygun kurulumu birlikte planlayalım.</p></div><div className="mt-12 grid gap-6 md:grid-cols-2">{[['Starter','Bulut POS, QR menü ve yönetim raporları.',['Masa ve sipariş yönetimi','Mutfak ekranı','QR menü','Stok, reçete ve fire','Tüm raporlamalar']],['Pro','Starter özelliklerine ek olarak yerinde yazıcı entegrasyonu.',['Starter paketindeki her şey','Termal mutfak fişi','Müşteri bilgi fişi','Yazıcı köprüsü kurulumu','Kurulum ve operasyon desteği']]].map(([name,desc,items],i)=><div key={name as string} className={`relative rounded-3xl bg-white p-8 ${i?'border-2 border-teal-600 shadow-xl':'border border-slate-200'}`}>{i===1&&<span className="absolute right-6 top-6 rounded-full bg-teal-600 px-3 py-1 text-xs font-bold text-white">Fiziksel kurulum</span>}<h3 className="font-display text-2xl font-bold">{name as string}</h3><p className="mt-2 text-slate-600">{desc as string}</p><ul className="mt-7 space-y-3 text-sm">{(items as string[]).map(x=><li key={x} className="flex gap-3"><Check className="text-teal-600" size={18}/>{x}</li>)}</ul></div>)}</div><div className="mt-9 text-center"><a href={`mailto:${CONTACT_EMAIL}?subject=Bi Restoran paket bilgisi`} className="inline-flex items-center gap-2 rounded-full bg-navy-900 px-7 py-4 font-bold text-white">Teklif ve kurulum bilgisi alın <ArrowRight size={18}/></a></div></div></section>
    <section id="sss" className="bg-white py-24"><div className="mx-auto max-w-4xl px-4 sm:px-6"><h2 className="text-center font-display text-4xl font-bold">Sık sorulanlar</h2><div className="mt-12 divide-y divide-slate-200 border-y border-slate-200">{[['Kurulum için program yüklemem gerekir mi?','Temel kullanım web üzerinden çalışır. Yalnızca fiziksel termal yazıcı kullanılacaksa restoran bilgisayarına güvenli yazıcı köprüsü kurulur.'],['Verilerim başka restoranlarla karışır mı?','Hayır. Her restoranın kullanıcıları, menüsü, siparişleri ve raporları tenant bazında izole edilir.'],['Telefon ve tablette çalışır mı?','Evet. Garson, mutfak, yönetim ve QR menü ekranları mobil cihazlara uyumludur.'],['14 gün sonra ne olur?','Deneme sonunda sizinle iletişime geçer, ihtiyacınıza uygun paketi birlikte belirleriz. Bilginiz dışında tahsilat yapılmaz.']].map(([q,a])=><div key={q} className="py-7"><h3 className="font-bold">{q}</h3><p className="mt-2 leading-7 text-slate-600">{a}</p></div>)}</div></div></section>
    <section className="bg-teal-600 py-20 text-white"><div className="mx-auto max-w-4xl px-4 text-center"><ShieldCheck className="mx-auto h-12 w-12"/><h2 className="mt-5 font-display text-4xl font-bold sm:text-5xl">Restoranınızı bugün dijitalleştirin.</h2><p className="mx-auto mt-5 max-w-2xl text-lg text-teal-50">Kredi kartı girmeden hesabınızı oluşturun ve 14 günlük deneme sürecini başlatın.</p><a href={`${APP_URL}/signup`} target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 rounded-full bg-white px-8 py-4 font-bold text-navy-900 shadow-xl">Ücretsiz Denemeyi Başlat <ExternalLink size={18}/></a></div></section>
  </main><footer className="bg-navy-900 py-10 text-slate-400"><div className="mx-auto flex max-w-7xl flex-col gap-6 px-4 text-sm md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-4"><img src="/bi-restoran-logo.jpg" alt="Bi Restoran" className="h-16 w-16 rounded-2xl bg-white object-cover"/><div><strong className="block text-lg text-white">Bi Restoran</strong><span>Bi Analytic tarafından geliştirilmiştir.</span></div></div><div className="flex flex-wrap gap-5"><a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a><a href={APP_URL}>Uygulamaya Giriş</a><a href="/">Bi Analytic</a></div><p>© {new Date().getFullYear()} Bi Analytic</p></div></footer></div>;
}
